### ISSUE TITLE
Publish npm package that can be installed without Mozilla auth.

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/lilypad#12]
It seems that installing Lilypad from github's package registry requires a personal access token (PAT) that is authorized with the Mozilla organization. I _think_ this is only possible for members of the Mozilla organization. 

Since we want lilypad to be publicly accessible, we may want to ask Mozilla where / how we can publish the npm package without requiring that authorization. (It's fine that the github registry requires a PAT, but anyone should be able to create one and use Lilypad -- not just those in the Mozilla organization.)

**Comment by nickgrato** [comment]
https://www.npmjs.com/package/@mozilla/lilypad-ui
